site_name: TestDocs
site_url: https://example.com/
repo_url: https://github.com/example/repository/
repo_name: boasvdp/test_docs

nav:
  - Home: index.md
  - About: about.md

# Basic config theming config settings
theme:
  name: material
  language: en

# version provider integrated with Material theme
extra:
  version:
    provider: mike